// Only installed catalog assets are remapped; custom admin image URLs remain intact.
const replacements: Record<string, string> = {
  "/sip-n-scoop/v9/cone-choco-block-brownie.webp": "/sip-n-scoop/premium/cone-choco-block-brownie.webp",
  "/sip-n-scoop/v9/cone-belgian-silky-chocolate.webp": "/sip-n-scoop/premium/cone-belgian-silky-chocolate.webp",
  "/sip-n-scoop/v9/cone-cookie-n-cream.webp": "/sip-n-scoop/premium/cone-cookie-n-cream.webp",
  "/sip-n-scoop/v9/cone-dark-chocolate.webp": "/sip-n-scoop/premium/cone-dark-chocolate.webp",
  "/sip-n-scoop/v9/cone-kesar-pista.webp": "/sip-n-scoop/premium/cone-kesar-pista.webp",
  "/sip-n-scoop/v9/cone-choco-brownie.webp": "/sip-n-scoop/premium/cone-choco-brownie.webp",
  "/sip-n-scoop/v9/cone-chocolate.webp": "/sip-n-scoop/premium/cone-chocolate.webp",
  "/sip-n-scoop/v9/cone-yummy-strawberry.webp": "/sip-n-scoop/premium/cone-yummy-strawberry.webp",
  "/sip-n-scoop/v9/cone-butter-scotch.webp": "/sip-n-scoop/premium/cone-butter-scotch.webp",
  "/sip-n-scoop/v9/cone-chic-chocolate.webp": "/sip-n-scoop/premium/cone-chic-chocolate.webp",
  "/sip-n-scoop/v9/cone-choco-vanilla.webp": "/sip-n-scoop/premium/cone-choco-vanilla.webp",
  "/sip-n-scoop/v9/cone-havmor-butter-scotch.webp": "/sip-n-scoop/premium/cone-havmor-butter-scotch.webp",
  "/sip-n-scoop/v9/cone-magic-butter-scotch.webp": "/sip-n-scoop/premium/cone-magic-butter-scotch.webp",
  "/sip-n-scoop/v9/bar-jumbo-crunchy-chocobar.webp": "/sip-n-scoop/premium/bar-jumbo-crunchy-chocobar.webp",
  "/sip-n-scoop/v9/bar-jumbo-classic-chocobar.webp": "/sip-n-scoop/premium/bar-jumbo-classic-chocobar.webp",
  "/sip-n-scoop/v9/bar-zulubar-dark-crunch.webp": "/sip-n-scoop/premium/bar-zulubar-dark-crunch.webp",
  "/sip-n-scoop/v9/bar-zulubar.webp": "/sip-n-scoop/premium/bar-zulubar.webp",
  "/sip-n-scoop/v9/dolly-jumbo-mango-dolly.webp": "/sip-n-scoop/premium/dolly-jumbo-mango-dolly.webp",
  "/sip-n-scoop/v9/dolly-jumbo-raspberry-dolly.webp": "/sip-n-scoop/premium/dolly-jumbo-raspberry-dolly.webp",
  "/sip-n-scoop/v9/fruit-aam.webp": "/sip-n-scoop/premium/fruit-aam.webp",
  "/sip-n-scoop/v9/ice-kachcha-aam.webp": "/sip-n-scoop/premium/ice-kachcha-aam.webp",
  "/sip-n-scoop/v9/ice-orange-bar.webp": "/sip-n-scoop/premium/ice-orange-bar.webp",
  "/sip-n-scoop/v9/cup-butter-scotch.webp": "/sip-n-scoop/premium/cup-butter-scotch.webp",
  "/sip-n-scoop/v9/cup-vanilla-85.webp": "/sip-n-scoop/premium/cup-vanilla-85.webp",
  "/sip-n-scoop/v9/cup-vanilla-50.webp": "/sip-n-scoop/premium/cup-vanilla-50.webp",
  "/sip-n-scoop/v9/cup-strawberry.webp": "/sip-n-scoop/premium/cup-strawberry.webp",
  "/sip-n-scoop/v9/cup-tutti-frutti.webp": "/sip-n-scoop/premium/cup-tutti-frutti.webp",
  "/sip-n-scoop/v9/sundae-choco-brownie.webp": "/sip-n-scoop/premium/sundae-choco-brownie.webp",
  "/sip-n-scoop/v9/sundae-choco.webp": "/sip-n-scoop/premium/sundae-choco.webp",
  "/sip-n-scoop/v9/sundae-strawberry.webp": "/sip-n-scoop/premium/sundae-strawberry.webp",
  "/sip-n-scoop/v9/jumbo-nutty-belgian-dark-chocolate.webp": "/sip-n-scoop/premium/jumbo-nutty-belgian-dark-chocolate.webp",
  "/sip-n-scoop/v9/jumbo-rajbhog.webp": "/sip-n-scoop/premium/jumbo-rajbhog.webp",
  "/sip-n-scoop/v9/jumbo-rajwadi-kulfi-falooda.webp": "/sip-n-scoop/premium/jumbo-rajwadi-kulfi-falooda.webp",
  "/sip-n-scoop/v9/jumbo-kesar-pista.webp": "/sip-n-scoop/premium/jumbo-kesar-pista.webp",
  "/sip-n-scoop/v9/jumbo-chocolate-chips.webp": "/sip-n-scoop/premium/jumbo-chocolate-chips.webp",
  "/sip-n-scoop/v9/jumbo-premium-kaju-kishmish.webp": "/sip-n-scoop/premium/jumbo-premium-kaju-kishmish.webp",
  "/sip-n-scoop/v9/jumbo-american-nuts.webp": "/sip-n-scoop/premium/jumbo-american-nuts.webp",
  "/sip-n-scoop/v9/jumbo-vanilla.webp": "/sip-n-scoop/premium/jumbo-vanilla.webp",
  "/sip-n-scoop/v9/jumbo-dark-chocolate-zero-sugar.webp": "/sip-n-scoop/premium/jumbo-dark-chocolate-zero-sugar.webp",
  "/sip-n-scoop/v9/jumbo-kesar-pista-zero-sugar.webp": "/sip-n-scoop/premium/jumbo-kesar-pista-zero-sugar.webp",
  "/sip-n-scoop/v9/jumbo-vanilla-zero-sugar.webp": "/sip-n-scoop/premium/jumbo-vanilla-zero-sugar.webp",
  "/sip-n-scoop/v9/kulfi-matka.webp": "/sip-n-scoop/premium/kulfi-matka.webp",
  "/sip-n-scoop/v9/kulfi-kashmiri-kesar.webp": "/sip-n-scoop/premium/kulfi-kashmiri-kesar.webp",
  "/sip-n-scoop/v9/kulfi-chowpaty.webp": "/sip-n-scoop/premium/kulfi-chowpaty.webp",
  "/sip-n-scoop/v9/kulfi-dryfruit-rabdi.webp": "/sip-n-scoop/premium/kulfi-dryfruit-rabdi.webp",
  "/sip-n-scoop/v9/kulfi-raj-bhog.webp": "/sip-n-scoop/premium/kulfi-raj-bhog.webp",
  "/sip-n-scoop/v9/kulfi-mava-tillewali.webp": "/sip-n-scoop/premium/kulfi-mava-tillewali.webp",
  "/sip-n-scoop/v9/kulfi-shahi.webp": "/sip-n-scoop/premium/kulfi-shahi.webp",
  "/sip-n-scoop/v9/kulfi-bombay.webp": "/sip-n-scoop/premium/kulfi-bombay.webp",
  "/sip-n-scoop/v9/kulfi-rajwadi.webp": "/sip-n-scoop/premium/kulfi-rajwadi.webp",
  "/sip-n-scoop/v9/kulfi-mava-malai.webp": "/sip-n-scoop/premium/kulfi-mava-malai.webp",
  "/sip-n-scoop/v9/kulfi-sf-malai.webp": "/sip-n-scoop/premium/kulfi-sf-malai.webp",
  "/sip-n-scoop/v9/brick-rajbhog.webp": "/sip-n-scoop/premium/brick-rajbhog.webp",
  "/sip-n-scoop/v9/brick-kesar-pista.webp": "/sip-n-scoop/premium/brick-kesar-pista.webp",
  "/sip-n-scoop/v9/brick-american-nuts.webp": "/sip-n-scoop/premium/brick-american-nuts.webp",
  "/sip-n-scoop/v9/brick-almond-carnival.webp": "/sip-n-scoop/premium/brick-almond-carnival.webp",
  "/sip-n-scoop/v9/brick-choco-brownie.webp": "/sip-n-scoop/premium/brick-choco-brownie.webp",
  "/sip-n-scoop/v9/brick-chocolate-chips.webp": "/sip-n-scoop/premium/brick-chocolate-chips.webp",
  "/sip-n-scoop/v9/brick-kaju-draksh.webp": "/sip-n-scoop/premium/brick-kaju-draksh.webp",
  "/sip-n-scoop/v9/brick-alphonso-mango.webp": "/sip-n-scoop/premium/brick-alphonso-mango.webp",
  "/sip-n-scoop/v9/brick-cookie-cream.webp": "/sip-n-scoop/premium/brick-cookie-cream.webp",
  "/sip-n-scoop/v9/brick-black-currant.webp": "/sip-n-scoop/premium/brick-black-currant.webp",
  "/sip-n-scoop/v9/brick-tutti-frutti.webp": "/sip-n-scoop/premium/brick-tutti-frutti.webp",
  "/sip-n-scoop/v9/brick-crunchy-butter-scotch.webp": "/sip-n-scoop/premium/brick-crunchy-butter-scotch.webp",
  "/sip-n-scoop/v9/brick-strawberry.webp": "/sip-n-scoop/premium/brick-strawberry.webp",
  "/sip-n-scoop/v9/brick-vanilla.webp": "/sip-n-scoop/premium/brick-vanilla.webp",
  "/sip-n-scoop/v9/brick-taj-mahal.webp": "/sip-n-scoop/premium/brick-taj-mahal.webp",
  "/sip-n-scoop/v9/brick-butterscotch-cookie.webp": "/sip-n-scoop/premium/brick-butterscotch-cookie.webp",
  "/sip-n-scoop/v9/brick-italian-cassata.webp": "/sip-n-scoop/premium/brick-italian-cassata.webp",
  "/sip-n-scoop/v9/independence-water-750.webp": "/sip-n-scoop/premium/independence-water-750.webp",
  "/sip-n-scoop/v9/bisleri-1l.webp": "/sip-n-scoop/premium/bisleri-1l.webp",
  "/sip-n-scoop/v9/sprite-1l.webp": "/sip-n-scoop/premium/sprite-1l.webp",
  "/sip-n-scoop/v9/coca-cola-1l.webp": "/sip-n-scoop/premium/coca-cola-1l.webp",
  "/sip-n-scoop/v9/thums-up-1l.webp": "/sip-n-scoop/premium/thums-up-1l.webp",
  "/sip-n-scoop/v9/thums-up-xforce-10.webp": "/sip-n-scoop/premium/thums-up-xforce-10.webp",
  "/sip-n-scoop/v9/campa-orange-10.webp": "/sip-n-scoop/premium/campa-orange-10.webp",
  "/sip-n-scoop/v9/campa-cola-10.webp": "/sip-n-scoop/premium/campa-cola-10.webp",
  "/sip-n-scoop/v9/raskik-nimbu-paani-10.webp": "/sip-n-scoop/premium/raskik-nimbu-paani-10.webp",
  "/sip-n-scoop/sip-coke-zero-10.svg": "/sip-n-scoop/premium/sip-coke-zero-10.webp",
  "/sip-n-scoop/sip-lemon-jeera-10.svg": "/sip-n-scoop/premium/sip-lemon-jeera-10.webp",
  "/sip-n-scoop/sip-frooti-10.svg": "/sip-n-scoop/premium/sip-frooti-10.webp"
};

const installedImages = new Set(Object.values(replacements));

export const resolveSipImage = (image: string): string => Object.hasOwn(replacements, image) ? replacements[image]! : image;

export const sipImageSrcSet = (image: string): string | undefined => {
  const source = resolveSipImage(image);
  return installedImages.has(source)
    ? `${source.slice(0, -5)}-480.webp 480w, ${source} 960w`
    : undefined;
};
